# Generated by Django 5.2.3 on 2025-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='like_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
